source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
gem 'puma', '~> 4.3'
gem 'mysql2', '~> 0.5.3'

gem 'bcrypt', '~> 3.1', '>= 3.1.16'
gem 'jwt', '~> 2.2', '>= 2.2.2'

gem 'delayed_job_active_record', '~> 4.1', '>= 4.1.4'
gem 'delayed_job_recurring', '~> 0.3.9'
gem 'terrapin', '~> 0.6.0'
gem 'posix-spawn', '~> 0.3.15'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :test do
  gem 'factory_bot_rails', '~> 4.0'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'faker'
  gem 'database_cleaner'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
